# File: azure-pipelines.yml
trigger: none

resources:
  pipelines:
    - pipeline: _BuildImageReleaseArtefacts
      source: Build Image Release Artefacts 3.0
  repositories:
    - repository: _lansa_azure_quickstart_templates
      type: github
      # endpoint: priyadishah
      name: lansa/azure-quickstart-templates
      ref: support/scalable
    - repository: _CelestialSystem_azure_quickstart_templates
      type: github
      # endpoint: priyadishah
      name: CelestialSystem/azure-quickstart-templates
      ref: feature/139
    - repository: _robe070_cookbooks
      type: github
      # endpoint: priyadishah
      name: robe070/cookbooks
      ref: debug/paas

variables:
  - group: Template Parameters
  - group: SKU Versions
  - group: Image Names
  - group: Azure Logins
  - group: Git Repos

stages:
- template: templates/debjit-stages.yml
  parameters:
    stageName: 'w12r2d142Aus'
    stagedisplayName: 'w12r2d142 Aus'
    jobName: 'w12r2d142Aus'
    jobDisplayname: 'w12r2d142 Aus'
    jobcondition: and(succeeded(), or(eq(variables['Build-w12r2d-14-2'], 'True'), eq(variables['Build-all'], 'True')))

- template: templates/debjit-stages.yml
  parameters:
    stageName: 'w12r2d150Aus'
    stagedisplayName: 'w12r2d150 Aus'
    jobName: 'w12r2d150Aus'
    jobDisplayname: 'w12r2d150 Aus'
    jobcondition: and(succeeded(), or(eq(variables['Build-w12r2d-15-0'], 'True'), eq(variables['Build-all'], 'True')))

- template: templates/debjit-stages.yml
  parameters:
    stageName: 'w16d142Aus'
    stagedisplayName: 'w16d142 Aus'
    jobName: 'w16d142Aus'
    jobDisplayname: 'w16d142 Aus'
    jobcondition: and(succeeded(), or(eq(variables['Build-w16d-14-2'], 'True'), eq(variables['Build-all'], 'True')))

- template: templates/debjit-stages.yml
  parameters:
    stageName: 'w16d150Aus'
    stagedisplayName: 'w16d150 Aus'
    jobName: 'w16d150Aus'
    jobDisplayname: 'w16d150 Aus'
    jobcondition: and(succeeded(), or(eq(variables['Build-w16d-15-0'], 'True'), eq(variables['Build-all'], 'True')))

- stage: 'PublishPreviewImages'
  displayName: 'Publish Preview Images'
  dependsOn: 
    - w12r2d150Aus
    - w12r2d142Aus
    - w16d142Aus
    - w16d150Aus
  jobs: 
  - job: 'AgentlessJob'
    displayName: 'Agentless job'
    pool: server
    steps:
    - task: ManualIntervention@8
      displayName: 'Publish Preview Images'
      inputs:
        instructions: |
          1. All preceding stages must be successful, or skipped
          2. Publish the preview images in the marketplace
          3. Wait for the email "Approve the offer preview for LANSA Scalable License"
          4. Increment the Version number in the Image Build Pipeline
          5. Increment the Test Version Preview Variable (TestVersionPrev<SKU>) in the "SKU Version" Variable Group.
          6. Only now the pipeline may be continued to test the preview images

- stage: 'MergePatch_PAASCookbooks'
  displayName: 'Merge patch/paas cookbooks'
  dependsOn: PublishPreviewImages
  jobs: 
  - job: 'MergePatch_PAASCookbooks'
    displayName: 'Merge patch/PAAS cookbooks'
    steps:

      - task: PowerShell@2
        displayName: 'Write access to Git Repo (robe070/cookbooks)'
        inputs:
          targetType: filePath
          filePath: '$(Pipeline.Workspace)/_robe070_cookbooks/scripts/GitRepoWriteAccess.ps1'
          arguments: '-GitBranch ''$(CookbooksBranchPreview)'' -GitURL ''https://$(GitRobe070CookbooksPAT):x-oauth-basic@$(GitRobe070CookbooksGitHubName)'' -GitUserEmail ''$(GitUserEmail)'' -GitUserName ''$(GitUserName)'' -GitRepoName ''$(CookbooksSourceAlias)'''

      - task: PowerShell@2
        displayName: 'Merge robe070/cookbooks repo debug/paas to patch/paas'
        inputs:
          targetType: filePath
          filePath: ' $(Pipeline.Workspace)/_robe070_cookbooks/scripts/GitMerge.ps1'
          arguments: '-GitRepoName ''$(CookbooksSourceAlias)'' -GitSourceBranch ''$(CookbooksBranch)'' -GitTargetBranch ''$(CookbooksBranchPreview)'''
      
- template: templates/debjit-stages.yml
  parameters:
    stageName: 'w12r2d142AusEastPreview'
    stagedisplayName: 'w12r2d142 Aus East Preview'
    jobName: 'w12r2d142AusEastPreview'
    jobDisplayname: 'w12r2d142 Aus East Preview'
    dependsOn: MergePatch_PAASCookbooks
    jobcondition: and(succeeded(), or(eq(variables['Build-w12r2d-14-2'], 'True'), eq(variables['Build-all'], 'True')))

- template: templates/debjit-stages.yml
  parameters:
    stageName: 'w12r2d142USEastPreview'
    stagedisplayName: 'w12r2d142 US East Preview'
    jobName: 'w12r2d142USEastPreview'
    jobDisplayname: 'w12r2d142 US East Preview'
    dependsOn: MergePatch_PAASCookbooks
    jobcondition: and(succeeded(), or(eq(variables['Build-w12r2d-14-2'], 'True'), eq(variables['Build-all'], 'True')))

- template: templates/debjit-stages.yml
  parameters:
    stageName: 'w12r2d142FranceCentralPreview'
    stagedisplayName: 'w12r2d142 France Central Preview'
    jobName: 'w12r2d142FranceCentralPreview'
    jobDisplayname: 'w12r2d142 France Central Preview'
    dependsOn: MergePatch_PAASCookbooks
    jobcondition: and(succeeded(), or(eq(variables['Build-w12r2d-14-2'], 'True'), eq(variables['Build-all'], 'True')))

- stage: 'GoLive'
  displayName: 'Go Live'
  dependsOn: 
    - w12r2d142AusEastPreview
    - w12r2d142USEastPreview
    - w12r2d142FranceCentralPreview
  jobs: 
  - job: 'AgentlessJob'
    displayName: 'Agentless job'
    pool: server
    steps:
    - task: ManualIntervention@8
      displayName: 'Publish Preview Images'
      inputs:
        instructions: |
          1. All preceding stages must be successful, or skipped
          2. Publish the preview images in the marketplace
          3. Wait for the email "Approve the offer preview for LANSA Scalable License"
          4. Increment the Version number in the Image Build Pipeline
          5. Increment the Test Version Preview Variable (TestVersionPrev<SKU>) in the "SKU Version" Variable Group.
          6. Only now the pipeline may be continued to test the preview images

- stage: 'CookbooksMergeAndTag'
  displayName: 'Cookbooks Merge & Tag'
  dependsOn: 'GoLive'
  jobs: 
  - job: 'CookbooksMergeAndTag'
    pool:
      vmImage: Windows-2022
    displayName: 'Cookbooks Merge & Tag'
    steps:
    - task: PowerShell@2
      displayName: 'Artifact Check: Set Gate Variable'
      name: Gate
      inputs:
        targetType: filePath
        filePath: '$(Pipeline.Workspace)/_robe070_cookbooks/scripts/azure_set_gate_variable.ps1'
        arguments: '-Version "w19d-15-0" -osName "Windows Server 2019"'

    - powershell: |
        # Print the Gate variables.
        if ( $(Gate.IsEnabled) -eq 'True' ) {
            Write-Host "Gate.IsEnabled: $(Gate.IsEnabled); Gate.ImageUrl: $(Gate.ImageUrl) Gate.Sku: $(Gate.Sku)" | Out-Default
        } 
      displayName: 'Artifact Check - Output Gate Variable'

    - task: PowerShell@2
      displayName: 'Write access to Git Repo (robe070/cookbooks)'
      inputs:
        targetType: filePath
        filePath: '$(Pipeline.Workspace)/_robe070_cookbooks/scripts/GitRepoWriteAccess.ps1'
        arguments: '-GitBranch ''$(CookbooksBranchLive)'' -GitURL ''https://$(GitRobe070CookbooksPAT):x-oauth-basic@$(GitRobe070CookbooksGitHubName)'' -GitUserEmail ''$(GitUserEmail)'' -GitUserName ''$(GitUserName)'' -GitRepoName ''$(CookbooksSourceAlias)'''

    - task: PowerShell@2
      displayName: 'Merge robe070/cookbooks repo patch/paas to support/scalable'
      inputs:
        targetType: filePath
        filePath: '$(Pipeline.Workspace)/_robe070_cookbooks/scripts/GitMerge.ps1'
        arguments: '-GitRepoName ''$(CookbooksSourceAlias)'' -GitSourceBranch ''$(CookbooksBranchPreview)'' -GitTargetBranch ''$(CookbooksBranchLive)'''

    - task: PowerShell@2
      displayName: 'Tag robe070/cookbooks repo '
      inputs:
        targetType: filePath
        filePath: '$(Pipeline.Workspace)/_robe070_cookbooks/scripts/GitTag.ps1'
        arguments: '-GitRepoName ''$(CookbooksSourceAlias)'' -Tags  ''AzureImage-Bld-$(Build.BuildId)-$(Release.ReleaseName)-$(Gate.Sku)'''

- template: templates/debjit-stages.yml
  parameters:
    stageName: 'w12r2d142USEastProduction'
    stagedisplayName: 'w12r2d142 US East Production'
    jobName: 'w12r2d142USEastProduction'
    jobDisplayname: 'w12r2d142 US East Production'
    dependsOn: CookbooksMergeAndTag
    jobcondition: and(succeeded(), or(eq(variables['Build-w12r2d-14-2'], 'True'), eq(variables['Build-all'], 'True')))

- template: templates/debjit-stages.yml
  parameters:
    stageName: 'w12r2d150AsiaEastProduction'
    stagedisplayName: 'w12r2d150 Asia East Production'
    jobName: 'w12r2d150AsiaEastProduction'
    jobDisplayname: 'w12r2d150 Asia East Production'
    dependsOn: CookbooksMergeAndTag
    jobcondition: and(succeeded(), or(eq(variables['Build-w12r2d-15-0'], 'True'), eq(variables['Build-all'], 'True')))

- template: templates/debjit-stages.yml
  parameters:
    stageName: 'w16d142EuropeWestProduction'
    stagedisplayName: 'w16d142 Europe West Production'
    jobName: 'w16d142EuropeWestProduction'
    jobDisplayname: 'w16d142 Europe West Production'
    dependsOn: CookbooksMergeAndTag
    jobcondition: and(succeeded(), or(eq(variables['Build-w16d-14-2'], 'True'), eq(variables['Build-all'], 'True')))
