parameters:
  - name: stageName
    type: string
    default: none
  - name: stageDisplayname
    type: string
    default: none
  - name: dependsOn
    default: []
  - name: jobName
    type: string
    default: none
  - name: vmImage
    type: string
    default: Windows-2022
  - name: resourceGroup
    type: string
    default: none
  - name: version
    type: string
    default: none
  - name: osName
    type: string
    default: none
  - name: lansaVersion
    type: string
    default: none 
  - name: imageId
    type: string
    default: none
  - name: imageSource
    type: string
    default: none
  - name: msiURL
    type: string
    default: none
  - name: stackName
    type: string
    default: none
  - name: certificateBase64Encoded
    type: string
    default: none
  - name: certificatePassword
    type: string
    default: none
  - name: databaseLogin
    type: string
    default: none
  - name: databaseLoginPassword
    type: string
    default: none
  - name: adminUsername
    type: string
    default: none
  - name: adminPassword
    type: string
    default: none
  - name: webUsername
    type: string
    default: none
  - name: webPassword
    type: string
    default: none
  - name: gitBranch
    type: string
    default: none
  - name: jobDemand
    type: string
    default: none

stages:
  - stage: ${{ parameters.stageName }}
    dependsOn: ${{ parameters.dependsOn }}
    displayName: ${{ parameters.stageDisplayname }}
    jobs:
    - job: ${{ parameters.jobName }}
      timeoutInMinutes: 120
      cancelTimeoutInMinutes: 1
      condition: ${{ parameters.jobcondition}}
      displayName: ${{ parameters.jobDisplayname }}

      pool:
        vmImage: ${{ parameters.vmImage }}
        demands: ${{ parameters.jobDemand }}

      steps:

      - download: _BuildImageReleaseArtefacts
        displayName: Downloading latest artefacts from Build Image Release Artefacts 3.0

      - checkout: _lansa_azure_quickstart_templates

      - checkout: _CelestialSystem_azure_quickstart_templates

      - checkout: _robe070_cookbooks

      - task: PowerShell@2
        displayName: 'Artifact Check: Set Gate Variable'
        name: Gate
        inputs:
          targetType: filePath
          filePath: '$(Pipeline.Workspace)/_robe070_cookbooks/scripts/azure_set_gate_variable.ps1'
          arguments: '-Version ${{ parameters.version }} -osName ${{ parameters.osName }}'

      - powershell: |
          # Print the Gate variables.
          Write-Host "Gate.IsEnabled: $(Gate.IsEnabled); Gate.ImageUrl: $(Gate.ImageUrl) Gate.Sku: $(Gate.Sku)" | Out-Default
        displayName: 'Artifact Check: Output Gate Variable'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'), or(eq(variables['Build-w12r2d-15-0'], 'True'), eq(variables['Build-all'], 'True')))

      - task: AzurePowerShell@5
        displayName: 'Delete resource group: ${{ parameters.resourceGroup }}'
        inputs:
          azureSubscription: 'Azure Baking Images'
          ScriptType: InlineScript
          Inline: |
            Write-Host Deleting Resource Group ${{ parameters.resourceGroup }}
            Remove-AzResourceGroup -Name ${{ parameters.resourceGroup }} -Force
          errorActionPreference: silentlyContinue
          azurePowerShellVersion: LatestVersion
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy ARM Template'
        inputs:
          azureResourceManagerConnection: 
          subscriptionId: '739c4e86-bd75-4910-8d6e-d7eb23ab94f3'
          resourceGroupName: '$(ResourceGroup)'
          location: 'Australia East'
          csmFile: '$(Pipeline.Workspace)/_lansa_azure-quickstart-templates/lansa-vmss-windows-autoscale-sql-database/mainTemplate.json'
          overrideParameters: '-osName ${{ parameters.osName }} -lansaVersion ${{ parameters.lansaVersion }} -imageId ${{ parameters.imageId }} -imageSource ${{ parameters.imageSource }} -msiURL ${{ parameters.msiURL }} -stackName ${{ parameters.stackName }} -certificateBase64Encoded ${{ parameters.certificateBase64Encoded }} -certificatePassword ${{ parameters.certificatePassword }} -databaseLogin ${{ parameters.databaseLogin }} -databaseLoginPassword ${{ parameters.databaseLoginPassword }} -adminUsername ${{ parameters.adminUsername }} -adminPassword ${{ parameters.adminPassword }} -webUsername ${{ parameters.webUsername }} -webPassword ${{ parameters.webPassword }} -gitBranch ${{ parameters.gitBranch }}'
          deploymentName: CustomTestTemplate
          deploymentOutputs: deploymentOutput
          addSpnToEnvironment: true
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      - task: maikvandergaag.maikvandergaag-azurergtag.azurergtag.azurergtag@1
        displayName: 'Azure Resource Group Tagging'
        inputs:
          ConnectedServiceName: 'Azure Baking Images'
          ResourceGroupName: ${{ parameters.resourceGroup }}
          Key: Usage
          Value: 'test-temp'
        continueOnError: true
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      - powershell: |
          # Print the Deployment Output
          Write-Host "$(deploymentOutput)" | out-default | Write-Verbose
        displayName: 'Print Deployment Output'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      - task: PowerShell@2
        displayName: 'Test ARM Deployment: URL Tests'
        inputs:
          targetType: filePath
          filePath: '$(Pipeline.Workspace)/_robe070_cookbooks/scripts/azure_url_tests.ps1'
          arguments: '-deploymentOutput none$(deploymentOutput)none'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      - task: AzurePowerShell@5
        displayName: 'Azure PowerShell: Test Image Version'
        inputs:
          azureSubscription: 'Azure Baking Images'
          ScriptPath: '$(Pipeline.Workspace)/_robe070_cookbooks/scripts/azure_test_image_version.ps1'
          ScriptArguments: '-SkuName "$(Gate.Sku)" -deploymentOutput none$(deploymentOutput)none '
          azurePowerShellVersion: LatestVersion
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Delete ResourceGroup'
        inputs:
          azureResourceManagerConnection: 
          subscriptionId: '739c4e86-bd75-4910-8d6e-d7eb23ab94f3'
          action: DeleteRG
          resourceGroupName: ${{ parameters.resourceGroup }}
        continueOnError: true
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))